Updated proposal to include RAF and Commit
junov/OffscreenCanvasAnimation pull request #3
Opened 2018-03-15 15:32 UTC by fserb

1st draft.

2018-03-19 14:36 UTC, junov requested changes

2018-03-19 14:36 UTC, junov commented on OffscreenCanvasAnimation.md
> +When `commit()` is called, a copy of the frame is made and sent to the driver/display when appropriate. This function can return immediately or block. The UA can decide to queue a few frames before b
Actually, we don't always make a copy. If it is a WebGL context with preserveDrawingBuffer = false, we transfer the frame instead.

2018-03-19 14:36 UTC, junov commented on OffscreenCanvasAnimation.md
> +* commit() supports the use case of a continuously running task that produces frames repeatedly over time, wihch enables the port of native application to the Web (e.g. via Emscripten).
wihch -> which

2018-03-19 14:36 UTC, junov commented on OffscreenCanvasAnimation.md
> +* commit() supports the use case of a continuously running task that produces frames repeatedly over time, wihch enables the port of native application to the Web (e.g. via Emscripten).
I think the context here could be developped a bit more. Should mention WASM, and how following an async model requires exiting and re-entering the WASM scope, which is bad.

2018-03-19 14:36 UTC, junov commented on OffscreenCanvasAnimation.md
> +When `commit()` is called, a copy of the frame is made and sent to the driver/display when appropriate. This function can return immediately or block. The UA can decide to queue a few frames before b
Missing: mechanism for throttling the frame rate

2018-03-19 15:17 UTC, fserb commented
Done. PTAL.

2018-03-19 15:48 UTC, junov requested changes

2018-03-19 15:48 UTC, junov commented on OffscreenCanvasAnimation.md
> +When `commit()` is called, the frame is sent to display. This function will block until another frame can be started to render. The UA can decide to queue a few frames before blocking to guarantee sm
there is no "guarantee", only hope.

2018-03-20 00:35 UTC, junov approved these changes

2018-03-20 00:35 UTC, merged